---
- hosts: 192.168.0.30
  user: root
  become: yes
  become_method: sudo
  gather_facts: yes

  tasks:
    - name: Install httpd and other required components
      yum: name={{ item }} state=latest
      with_items:
        - httpd
        - httpd-manual
        - elinks
        - firewalld
      notify:
        - Restart firewalld service


    - name: Copy index.html and vhosts1.conf file to destination (provides hostname)
      template: src={{ item.src }} dest={{ item.dest }} owner=root group=root mode=0666
      with_items:
        - src: index.html.j2
          dest: /var/www/html/index.html
        - src: vhosts.conf.j2
          dest: /etc/httpd/conf.d/{{ ansible_nodename }}.conf


    - name: Add http/https to firewalld
      firewalld: service={{ item }} permanent=yes state=enabled
      with_items:
        - http
        - https
      notify:
        - Restart httpd service


  handlers:
    - name: Restart firewalld service
      service: name=firewalld state=restarted enabled=yes
     
    - name: Restart httpd service
      service: name=httpd state=restarted enabled=yes
